version: '2'

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1

services:
  redis_master:
    container_name: redis_master_1
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.1.1
    ports:
      - '6379:6379'
      - '26375:26379'
      - '5000:5000'
    privileged: true
    restart: unless-stopped
    command: ['tail', '-F', 'anything']

  redis_slave:
    container_name: redis_slave_1
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.2.1
    ports:
      - '6378:6379'
      - '26376:26379'
    privileged: true
    restart: unless-stopped
    command: ['tail', '-F', 'anything']
  redis_sentinel:
    container_name: redis_sentinel_1
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      vpcbr:
        ipv4_address: 10.5.3.1
    ports:
      - '6377:6379'
      - '26377:26379'
    privileged: true
    restart: unless-stopped
    command: ['tail', '-F', 'anything']
